/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jlab.femodeler;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        String string = "Heyo!";
        assertNotNull("app should have a greeting", string);
    }
}
